# Generated by Django 5.0.3 on 2024-03-16 13:32

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0003_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('group_name', models.CharField(max_length=250, verbose_name='Group name')),
                ('pupils_count', models.IntegerField(default=0)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ClassRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('class_name', models.CharField(max_length=250)),
                ('capacity', models.PositiveIntegerField(default=0)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='class_rooms', to='common.school', verbose_name='School')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='class_rooms', to='common.group', verbose_name='Group')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Pupil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('full_name', models.CharField(max_length=250, verbose_name='Full name')),
                ('birthday', models.DateField()),
                ('phone_number', models.CharField(max_length=13, validators=[django.core.validators.RegexValidator(message='Invalid phone number', regex='^/+998/d{9}$')], verbose_name='Phone number')),
                ('parent_full_name', models.CharField(max_length=500, verbose_name='Parent full name')),
                ('parent_number', models.CharField(max_length=13, validators=[django.core.validators.RegexValidator(message='Invalid phone number', regex='^/+998/d{9}$')], verbose_name='Parent phone number')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pupils', to='common.group', verbose_name='Group')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pupils', to='common.school', verbose_name='School')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('full_name', models.CharField(max_length=250, verbose_name='Full name')),
                ('phone_number', models.CharField(max_length=13, validators=[django.core.validators.RegexValidator(message='Invalid phone number', regex='^/+998/d{9}$')], verbose_name='Phone number')),
                ('experience', models.IntegerField(default=0, verbose_name='Experience')),
                ('birthday', models.DateField()),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='teachers', to='common.group', verbose_name='Class Group')),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='teachers', to='common.position', verbose_name='Position')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='teachers', to='common.school', verbose_name='School')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='group',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='groups', to='common.teacher', verbose_name='Teacher'),
        ),
    ]
