# Generated by Django 5.0.3 on 2024-03-17 05:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_birthday'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(max_length=13, validators=[django.core.validators.RegexValidator(message='Invalid phone number', regex='^\\+998\\d{9}$')], verbose_name='Phone number'),
        ),
    ]
